### ISSUE TITLE
design

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/hadith#10]
- [x] plan architecture 
- [x] sort & clean up thing
- [x] timebox & deadline
- [x] index(book wise(lang group) page (30mins)
- [x] section page  (30mins)
- [x] single/chap(sec)/full (edition,type,grade unianimous) (30mins)
- [x] grade (filter logic)
- [x] revert changes for previous functinality
- [x] [seo listing gen](https://github.com/fawazahmed0/hadith/issues/10#issuecomment-1111059128)
- [x] individual listing page(so google can find without sitemap generation) (by hadnum with all langs
- [x] only keep single visible to google to avoid duplicates (& get good results) (divide by book(using nums [crc](https://www.npmjs.com/package/crc) 65k pregenerated) & then language) (using noindex tag for pages not required maybe) (isocodes all languages pregenerate) (bookname in query for seo)
- [x] Group by language in single results page for ease
- [x] Easy scroll using jump to lang, and group by lang
- [x] see [seo html attribures like lang & dir etc for single elments](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes)
- [x] add the seo attr in data.html also
- [x] autoget bare edition if not found
- [x] google site search (30mins)
- [x] fallbak
- [x] avoid sitemap, link seo.html page in sections page with name Get Single Hadith with multiple Languages at very bottom
- [x] [sitemap ](https://github.com/fawazahmed0/hadith/issues/10#issuecomment-1108813821)(query params)(avoid duplictes for better g-search) (sitemap link to seo page) (30mins)
- [x] run functions after domcontentloaded (see letters script)
- [x] refactor code
- [x] fetch parallel
- [x] mustache template (see letters)
- [x] noindex tag
- [x] seo (dynamic)  (docusaurus)(seei18n, meta tags, frontmatters), see letters proj for seo etc  (30mins)
- [x] use [common tags](https://github.com/fawazahmed0/hadith/issues/10#issuecomment-1112576817)
- [x] clean UI
- [x] test
- [x] documentation
- [x] qura (60mins) (try to use old app , code in new page) (new page to search this, keep it at islm-projs)

**design:**
grades and list of graders names and grades
Grades:
albani: ....

publish @ hadiths repo
Deadline: 27-04-22

**Comment by fawazahmed0** [comment]
add demo in h-api, with link to docu site

**Comment by fawazahmed0** [comment]
also for qura seo,

also refer to see what things can be integrated

**Comment by fawazahmed0** [comment]
actions scirpt due to lots of file getting generated

**Comment by fawazahmed0** [comment]
use bootstrap, it's easy, 
use docusaurus seo things (seei18n, meta tags, frontmatters), see letters proj for seo etc

**Comment by fawazahmed0** [comment]
pregenerate 30k for single (same file), to make it dynamic to fetch any, without rebuild

**Comment by fawazahmed0** [comment]
create & use hadiths repo, due to space, disable pages & cloudflare pages in opd hadith repo

tag implementation similar to docu to make things easier

also see how it generates sitemap, for search engines to find, so i can do same

**Comment by fawazahmed0** [comment]
sort & clean up things

**Comment by fawazahmed0** [comment]
Decide and do things fast
Keep all lang together Might be better idea , for everyone 
Use query param for book With autogenrated link on page
From book pahe to new page with query param with individual hadith index page link dynamically generated 
Set lang , dir etc for each individual hadith for seo & set other things for individual for seo

**Comment by fawazahmed0** [comment]
Search engines rely on the HTML markup such as <h2>, <table>, etc., to understand the structure of your webpage. When Docusaurus renders your pages, semantic markup, e.g. <aside>, <nav>, <main>, are used to divide the different sections of the page, helping the search engine to locate parts like sidebar, navbar, and the main page content.

**Comment by fawazahmed0** [comment]
search bar in q
footer, see verse by verse link, page with all chap x verse x links,
seoify same as had prof
also add search bar on data single verse listings page
and also maybe on dataseo had proj page

**Comment by fawazahmed0** [comment]
add sections nane in section listing
show section num &  name only if type is section
see margin/padding in phone
